#!/usr/bin/env python3
"""Generate content-hash map for cache-busting mutable static assets.

Run after replacing files under assets/collections/ or assets/coming-soon.png:

  python3 scripts/update-asset-versions.py

Commits should include the regenerated js/asset-versions.js so deploys change
collection cover URLs (?v=<hash>) and returning browsers fetch the new bytes
even if they previously cached the unversioned URL as immutable.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "js" / "asset-versions.js"


def short_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:12]


def main() -> None:
    hashes: dict[str, str] = {}

    covers = ROOT / "assets" / "collections"
    if covers.is_dir():
        for path in sorted(covers.glob("*.png")):
            hashes[path.name] = short_hash(path)

    coming_soon = ROOT / "assets" / "coming-soon.png"
    if coming_soon.is_file():
        hashes[coming_soon.name] = short_hash(coming_soon)

    payload = json.dumps(hashes, indent=2, sort_keys=True)
    OUT.write_text(
        "// Auto-generated by scripts/update-asset-versions.py — do not edit by hand.\n"
        "// Re-run after replacing assets/collections/*.png or assets/coming-soon.png.\n"
        f"export const ASSET_CONTENT_HASHES = {payload};\n"
    )
    print(f"Wrote {len(hashes)} content hashes → {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
