#!/usr/bin/env python3
"""Site-wide content hashes for cache-busting /assets/* URLs.

Cloudflare Pages does not fingerprint filenames (no bundler). Stable paths under
assets/ are safe to mark immutable in `_headers` only when every reference
includes ?v=<content-hash>.

Run after adding/replacing any file under assets/:

  python3 scripts/update-asset-versions.py

This script:
  1. Writes js/asset-versions.js (pathname → sha256-12)
  2. Rewrites ?v= on asset refs in HTML + styles.css (idempotent)

JS/JSON runtime refs are versioned via withAssetContentHash() / loadJSON hydrate.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
OUT_JS = ROOT / "js" / "asset-versions.js"

# Match local asset paths in HTML/CSS (with optional existing ?v=).
ASSET_REF_RE = re.compile(
    r"""(?P<prefix>(?:src|href)=["']|\burl\(\s*["']?)"""
    r"""(?P<path>\.?/?assets/[^"'\)\s?#]+)"""
    r"""(?:\?v=[0-9a-f]+)?"""
    r"""(?P<suffix>["']|\s*\))""",
    re.IGNORECASE,
)


def short_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:12]


def collect_hashes() -> dict[str, str]:
    hashes: dict[str, str] = {}
    if not ASSETS.is_dir():
        return hashes
    for path in sorted(ASSETS.rglob("*")):
        if not path.is_file():
            continue
        if path.name == "README.md" or path.name.startswith("."):
            continue
        rel = path.relative_to(ROOT).as_posix()  # assets/...
        hashes[f"/{rel}"] = short_hash(path)
    return hashes


def lookup_hash(hashes: dict[str, str], raw_path: str) -> str | None:
    cleaned = raw_path.strip().split("?")[0].replace("\\", "/")
    cleaned = cleaned[2:] if cleaned.startswith("./") else cleaned
    cleaned = cleaned.lstrip("/")
    if not cleaned.startswith("assets/"):
        return None
    return hashes.get(f"/{cleaned}")


def rewrite_text(text: str, hashes: dict[str, str]) -> tuple[str, int]:
    changes = 0

    def repl(match: re.Match[str]) -> str:
        nonlocal changes
        raw = match.group("path")
        digest = lookup_hash(hashes, raw)
        if not digest:
            return match.group(0)
        # Normalize to the same relative/absolute style the source used.
        path_only = raw.split("?")[0]
        versioned = f"{path_only}?v={digest}"
        if versioned == f"{path_only}?v={digest}" and match.group(0).endswith(
            f"?v={digest}{match.group('suffix')}"
        ):
            # Still count as ensuring correctness; only bump when different.
            old = match.group(0)
            new = f"{match.group('prefix')}{versioned}{match.group('suffix')}"
            if old != new:
                changes += 1
            return new
        new = f"{match.group('prefix')}{versioned}{match.group('suffix')}"
        if new != match.group(0):
            changes += 1
        return new

    return ASSET_REF_RE.sub(repl, text), changes


def rewrite_files(hashes: dict[str, str]) -> int:
    total = 0
    targets: list[Path] = []
    targets.extend(sorted(ROOT.glob("*.html")))
    targets.extend(sorted((ROOT / "admin").glob("*.html")))
    targets.append(ROOT / "styles.css")
    for path in targets:
        if not path.is_file():
            continue
        original = path.read_text(encoding="utf-8")
        updated, n = rewrite_text(original, hashes)
        if n and updated != original:
            path.write_text(updated, encoding="utf-8")
            total += n
            print(f"  updated {path.relative_to(ROOT)} ({n} refs)")
    return total


def write_versions_module(hashes: dict[str, str]) -> None:
    payload = json.dumps(hashes, indent=2, sort_keys=True)
    OUT_JS.write_text(
        "// Auto-generated by scripts/update-asset-versions.py — do not edit by hand.\n"
        "// Re-run after adding/replacing any file under assets/.\n"
        f"export const ASSET_CONTENT_HASHES = {payload};\n",
        encoding="utf-8",
    )


def main() -> None:
    hashes = collect_hashes()
    write_versions_module(hashes)
    print(f"Wrote {len(hashes)} content hashes → {OUT_JS.relative_to(ROOT)}")
    n = rewrite_files(hashes)
    print(f"Rewrote {n} HTML/CSS asset references")


if __name__ == "__main__":
    main()
